name: Test rule-keeper and check post validity and tags recommendations

on:
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Fetch history of master branch
        run: git fetch origin master:master --depth=1
      - name: Build docker image
        run: docker build ./rule-keeper/ -t rule-keeper
      - name: Test Rule Keeper
        run: docker run -v ./rule-keeper:/usr/src/app:ro rule-keeper python -m unittest
      - name: Test content
        run: docker run -v .:/usr/src/app:ro rule-keeper  python rule-keeper/main.py
